name: anki_flutter
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  dartx: ^1.0.0
  flutter:
    sdk: flutter
  flutter_html: ^2.2.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  get_it_mixin: ^3.1.3
  path_provider: ^2.0.8
  sembast: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  freezed: ^1.1.1
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  # assets:
  #   - assets/images/
